services:
  web:
    container_name: ours.web
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      MARIADB_HOST: db
      MARIADB_PORT: 3306
      MARIADB_DATABASE: ours
      MARIADB_USERNAME: ${OURS_MARIADB_USERNAME}
      MARIADB_PASSWORD: ${OURS_MARIADB_PASSWORD}
    links:
      - db
      - redis

  db:
    container_name: ours.mariadb_master
    image: mariadb:10.11.4
    restart: always
    environment:
      MYSQL_DATABASE: ours
      MYSQL_USER: ${OURS_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${OURS_MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${OURS_MARIADB_ROOT_PASSWORD}
    ports:
        - "3307:3306"
    volumes:
        - ./mariadb_master/data:/var/lib/mysql
        - ./mariadb_master/conf:/etc/mysql/conf.d
        - ./mariadb_master/logs:/var/log/mysql

  redis:
    container_name: ours.redis
    image: redis:7.0.12
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/var/log/redis